spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
