spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092

#    flyway:
#      baseline-on-migrate: true
#      enabled: true
#      baseline-description: "init"
#      baseline-version: 0
#      user: ${spring.datasource.username}
#      password: ${spring.datasource.password}

  application:
    config:
      kafka:
        payment-topic: payment-topic

server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

application:
  config:
    customer-service-url: http://localhost:9090/api/customers


